
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.6.0
  creationTimestamp: null
  name: katalystagentconfigs.config.katalyst.kubewharf.io
spec:
  group: config.katalyst.kubewharf.io
  names:
    kind: KatalystAgentConfig
    listKind: KatalystAgentConfigList
    plural: katalystagentconfigs
    shortNames:
    - kac
    singular: katalystagentconfig
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    - jsonPath: .spec.nodeLabelSelector
      name: SELECTOR
      type: string
    - jsonPath: .spec.ephemeralSelector.nodeNames
      name: NODES
      type: string
    - jsonPath: .spec.ephemeralSelector.lastDuration
      name: DURATION
      type: string
    - jsonPath: .status.conditions[?(@.type=="Valid")].status
      name: VALID
      type: string
    - jsonPath: .status.conditions[?(@.type=="Valid")].reason
      name: REASON
      type: string
    - jsonPath: .status.conditions[?(@.type=="Valid")].message
      name: MESSAGE
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: KatalystAgentConfig is the Schema for the configuration API used
          by katalyst agent
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: KatalystAgentConfigSpec defines the desired state of KatalystAgentConfig
            properties:
              config:
                description: Config is custom field for agent configuration all configuration
                  crd should contain a field named with `config`
                properties:
                  memoryEvictionPluginConfig:
                    description: MemoryEvictionPluginConfig is the config for memory
                      eviction plugin
                    properties:
                      enableNumaLevelDetection:
                        description: EnableNumaLevelDetection is whether to enable
                          numa-level detection
                        type: boolean
                      enableSystemLevelDetection:
                        description: EnableSystemLevelDetection is whether to enable
                          system-level detection
                        type: boolean
                      gracePeriod:
                        description: GracePeriod is the grace period of memory eviction
                        format: int64
                        type: integer
                      numaEvictionRankingMetrics:
                        description: NumaEvictionRankingMetrics is the metrics used
                          to rank pods for eviction at the NUMA level
                        items:
                          type: string
                        type: array
                      numaFreeBelowWatermarkTimesThreshold:
                        description: NumaFreeBelowWatermarkTimesThreshold is the threshold
                          for the number of times NUMA's free memory falls below the
                          watermark
                        type: integer
                      systemEvictionRankingMetrics:
                        description: SystemEvictionRankingMetrics is the metrics used
                          to rank pods for eviction at the system level
                        items:
                          type: string
                        type: array
                      systemKswapdRateExceedTimesThreshold:
                        description: SystemKswapdRateExceedCountThreshold is the threshold
                          for the number of times the kswapd reclaiming rate exceeds
                          the threshold
                        type: integer
                      systemKswapdRateThreshold:
                        description: NumaFreeBelowWatermarkTimesThreshold is the threshold
                          for the rate of kswapd reclaiming rate
                        type: integer
                    type: object
                  reclaimedResourcesEvictionPluginConfig:
                    description: reclaimed resources eviction plugin options
                    properties:
                      evictionThreshold:
                        additionalProperties:
                          type: number
                        description: eviction threshold rate for reclaimed resources
                        type: object
                    type: object
                type: object
              ephemeralSelector:
                description: EphemeralSelector is used to indicate the
                properties:
                  lastDuration:
                    description: define the duration this configuration will last
                      from creationTimestamp. must and only set when NodeNames already
                      set
                    type: string
                  nodeNames:
                    description: Specific nodes' name the configurations will be effected.
                    items:
                      type: string
                    type: array
                type: object
              nodeLabelSelector:
                description: NodeLabelSelector select nodes to apply these configurations
                  if spec.labelKey no set, NodeLabelSelector must be empty the label
                  selector must only include KatalystAgentConfig.spec .nodeLabelSelectorKey,
                  otherwise it will not be synced This field will be immutable after
                  it is initially set.
                type: string
              revisionHistoryLimit:
                default: 3
                description: RevisionHistoryLimit is the maximum number of revisions
                  that will be maintained in the resource's revision history. The
                  revision history consists of all revisions not represented by a
                  currently applied Spec version. The default value is 3.
                format: int64
                type: integer
            type: object
          status:
            properties:
              collisionCount:
                description: Count of hash collisions for this cr. The kcc controller
                  uses this field as a collision avoidance mechanism when it needs
                  to create the name for the newest ControllerRevision.
                format: int32
                type: integer
              conditions:
                description: Represents the latest available observations of a config's
                  current state.
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transit from one status
                        to another.
                      format: date-time
                      type: string
                    message:
                      description: message is a human-readable explanation containing
                        details about the transition
                      type: string
                    reason:
                      description: reason is the reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of config condition
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: The most recent generation observed by the kcc controller.
                format: int64
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
